services:
  - type: redis
    name: redis-celery
    ipAllowList: [] # Allow all access

  - type: web
    name: job-scheduler
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn worker_2:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis-celery
          property: connectionString
      - key: MAILTRAP_USER
        sync: false
      - key: MAILTRAP_PASS
        sync: false

  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis-celery
          property: connectionString
      - key: MAILTRAP_USER
        sync: false
      - key: MAILTRAP_PASS
        sync: false
